### ISSUE TITLE
List of Cocktails/Drinks

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#1]
## Value proposition

**As a** user
**I need** to have a list of Cocktails/Drinks
**to be able to** to get inspiration for the next cocktail night

## Description
![Wireframe List of Cocktails_Drinks](https://user-images.githubusercontent.com/97166823/156580866-6e1f760c-d051-463d-801f-955b4dc1f4c2.png)

## Acceptance Criteria

- [ ] the list is scrollable
- [ ] each cocktail/drink has a list of ingredients and a description text

## Tasks

- [ ] Global Styles
- [ ] fetch data for list
- [ ] create components/Header
    - [ ] component / styled components
    - [ ] storybook
    - [ ] tests
- [ ] create components/Drink
    - [ ] component / styled components
    - [ ] storybook
    - [ ] tests
- [ ] add to app
- [ ] check on mobile device
- [ ] check accessibility
