### ISSUE TITLE
Searchbar / search function

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#10]
## Value proposition

**As a** user
**I need** to search for drinks
**to be able to** get faster to requested drinks

## Description
![Cocktails Searchbar](https://user-images.githubusercontent.com/97166823/157697966-5f0162d0-df13-4873-9752-c94745a75054.png)

## Acceptance Criteria

- [ ] under the header should be a searchbar above the list of drinks
- [ ] after every change of the input the whole list should be filtered with the input
- [ ] the filtered data will listed under the searchbar
- [ ] when the searchbar input is empty all drinks should be listed

## Tasks

- [ ] components/Searchbar
    - [ ] component
    - [ ] storybook
    - [ ] test
- [ ] add onChange function for filtering the data
- [ ] edit the drinklist page to render the whole data or the filtered data regarding to the input value
- [ ] add to app
- [ ] check on mobile device
- [ ] check accessibility
