### ISSUE TITLE
Filter for alcoholic / non-alcoholic drinks

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#13]
## Value proposition

**As a** user
**I need** to filter the drinks
**to be able to** get either all, alcoholic or non-alcoholic drinks

## Description
![Cocktails Filter](https://user-images.githubusercontent.com/97166823/157881181-797e6770-89cc-4c9c-8c0a-2a8df93a12a6.png)

## Acceptance Criteria

- [x] under the searchbar should be a filter above the list of drinks
- [x] on the bookmark page the filter should be on top to filter the bookmarked drinks
- [x] by clicking on one of the filter options, the actual drinks list will be filtered by the chosen value

## Tasks

- [x] components/Filter
    - [x] component
    - [x] story
    - [x] test
- [x] add onChange function for filtering the data
- [x] edit the drinkList to render the data in relation to the chosen filters (search value and chosen filter)
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
