### ISSUE TITLE
Details page for every drink / cleaned up drinklist with less data (name, small image, category, alcoholic/non-alcoholic)

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#14]
## Value proposition

**As a** user
**I need** to see the details for every drink on a separate page
**to be able to** get a cleaned up overview in the drinklist with less information on a quick look

## Description
![Cocktails SingleDrinkPage](https://user-images.githubusercontent.com/97166823/157883324-19e130d2-6437-4df2-9058-fc4ad96b79d3.png)

## Acceptance Criteria

- [x] on the Drink List Page and the Bookmark Page should be a list of drinks with less details (name, image, etc.)
- [x] by clicking on a drink the user reach a separate page with more details of the drink (name, image, ingredients, instructions)
- [x] by clicking on the back link the user gets back to the list he was before

## Tasks

- [x] create page for single drink with all needed elements to show the user / add go back function
- [x] add onClick function for the drinkCards to get to the separate drink page
- [x] edit the DrinkCard and reduce details for the drinkList and bookmark page
- [x] add test for the single drink page if all elements will render
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
