### ISSUE TITLE
Loading / intro page when start or refresh the App

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#15]
## Value proposition

**As a** user
**I need** to get a loading page when open the app
**to be able to** avoid a blank page while loading the data for a better user experience

## Description
![Cocktails LoadingPage](https://user-images.githubusercontent.com/97166823/157895797-774324cb-39c4-4bde-85ba-f67cdb239f31.png)

## Acceptance Criteria

- [ ] an intro page when open (or refresh) the app while loading the data
- [ ] the intro Page should show the title of the app
- [ ] for illustration the intro page has a topic related image

## Tasks

- [ ] create intro page with title and image
- [ ] add logic with a loading state to the app which set to false after loading the data
- [ ] add to app
- [ ] check on mobile device
- [ ] check accessibility
