### ISSUE TITLE
Images for every Cocktail/Drink

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#2]
## Value proposition

**As a** user
**I need** to have small images for every drink in the list
**to be able to** get an idea of its look

## Description
![Cocktails add images](https://user-images.githubusercontent.com/97166823/156597092-a402f101-5e30-4ebb-97e2-806d01c90ebd.png)

## Acceptance Criteria

- [x] each cocktail/drink has a small image for illustration

## Tasks

- [x] edit components/Drink
    - [x] component / styled components
    - [x] storybook
    - [x] tests
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
