### ISSUE TITLE
Delete Function 

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#21]
## Value proposition

**As a** user
**I need** to delete my drinks
**to be able to** keep the data clean and remove drinks no more needed

## Description
![Cocktails DeleteDrink](https://user-images.githubusercontent.com/97166823/159134707-d608480f-7507-423e-ab9f-7b26b09e8d87.png)

## Acceptance Criteria

- [x] delete button for the created drinks
- [x] a modal to verify the deletion
- [x] an updated list of the drinks after deleted one

## Tasks

- [x] edit drink cards with delete button
- [x] create modal for confirmation
    - [x] component
    - [x] story
    - [x] test
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
