### ISSUE TITLE
Get a random drink

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#23]
## Value proposition

**As a** user
**I need** to get random drinks
**to be able to** to have a fun feature and get a surprise

## Description
![Cocktails RandomDrink](https://user-images.githubusercontent.com/97166823/159135474-c5ed73a2-c11d-4f1b-b6f8-258cdeae9025.png)

## Acceptance Criteria

- [x] new page for getting random drinks
- [x] when reaching the page the first random drink will be fetched and rendered
- [x] a button renders a random drink from the api every time when be clicked 

## Tasks

- [x] create new page for random drink function
- [x] add logic with onClick function and data fetching
- [x] edit navigation
- [x] add test
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
