### ISSUE TITLE
Rating function with notes

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#24]
## Value proposition

**As a** user
**I need** to rate already tested drinks
**to be able to** get a reminder and information which drink already tested and know which one tasted good or not

## Description
![Cocktails RatingDrink](https://user-images.githubusercontent.com/97166823/159136245-7a286592-a09a-429c-863a-e36a6f30eb54.png)

## Acceptance Criteria

- [x] drink page with a rating section with the possibility to draw some notes and the bottom of the page
- [x] rating with stars (or drinks) or percent value

## Tasks

- [x] edit drink page and tests/story
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
