### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#27]
## Value proposition

**As a** user
**I need** a better styling
**to be able to** have a better visual experience when using the app

## Description
Changes in styling (colors, structure, positioning)
## Acceptance Criteria

- [ ] new colors in modern design
- [ ] header with different titles on all pages
- [ ] navigation fixed at the bottom on every page, not on drink page and create form

## Tasks

- [ ] edit app grid
- [ ] change colors
- [ ] edit styling of single pages
