### ISSUE TITLE
Show and hide details for every drink

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#3]
## Value proposition

**As a** user
**I need** to show and hide the details of every drink in the list
**to be able to** get a cleaned up list of drinks

## Description
![Cocktails ShowHideToggle(1)](https://user-images.githubusercontent.com/97166823/156597365-e69c9c3a-728b-43ed-99ca-f40f599ca972.png)

## Acceptance Criteria

- [x] each cocktail/drink has a toggle button for showing/hiding details

## Tasks

- [x] edit components/Drinks
    - [x] component
    - [x] storybook
    - [x] tests
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
