### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#31]
## Value proposition

**As a** user
**I need** to have a scroll to top button
**to be able to** get quick to the top after scrolling down the list of drinks

## Description
![Cocktails ScrollToTop](https://user-images.githubusercontent.com/97166823/160369260-402a8a37-f8da-4aa8-8e15-e159ee8cdb88.png)

## Acceptance Criteria

- [x] on the pages (drink list, favorites, my drinks) a scroll to top button appears at the bottom after scrolling a little bit
- [x] by clicking on the scroll to top button the user gets to the beginning of the page

## Tasks

- [x] create component/scrollToTopButton
    - [x] component
    - [x] story
    - [x] test
- [x] add logic for clicking the button
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
