### ISSUE TITLE
Shopping List for selected drinks

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#33]
## Value proposition

**As a** user
**I need** to get a list of ingredients for selected drinks
**to be able to** know which ingredients I need to get to prepare these drinks

## Description
![Cocktails ShoppingList](https://user-images.githubusercontent.com/97166823/160370373-8fa7d564-4403-4fbf-a550-5d5f46de257c.png)

## Acceptance Criteria

- [x] new page for creating a shopping list for selected drinks
- [x] drinks can be searched and added to list with a searchbar
- [x] while typing the user gets suggestions for drinks
- [x] added drinks will be listed below the searchbar
- [x] by clicking on a button a shopping list with all needed ingredients will be created and displayed below the list of drinks

## Tasks

- [x] create page/ShoppingList
- [x] create component/Searchbar with auto suggestion 
- [x] create component/ShoppingList for the ingredients 
- [x] add logic for creating the shopping list items for selected drinks
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
