### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#34]
## Value proposition

**As a** developer
**I need** to have clean code
**to be able to** to reduce the amount of code and have a better overview over the whole app

## Acceptance Criteria

- [ ] reduce code (DRY)
- [ ] create single functions for reused components (like buttons)

## Tasks

- [ ] refactor the code as good as possible
