### ISSUE TITLE
Bookmark/Bookmarked-Page

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#4]
## Value proposition

**As a** user
**I need** to bookmark drinks
**to be able to** get a separate list of bookmarked drinks

## Description
![Cocktails Bookmark(1)](https://user-images.githubusercontent.com/97166823/156606351-d29b6f31-9a5d-42f8-9946-80341bb6c0a2.png)

## Acceptance Criteria

- [x] each cocktail/drink has a toggle bookmark button
- [x] bookmarked drinks appear at a separate list
- [x] drinks disappear from the bookmarked page after remove the bookmark
- [x] bookmark page shows an empty state if nothing is bookmarked
- [x] both pages should be reached by clicking on a navigation button

## Tasks

- [x] edit components/Drink
- [x] add components/Navigation
    - [x] component
    - [x] story
    - [x] test
- [x] add pages for the main list and bookmarked list
    - [x] add button to navigate between both pages
    - [x] add empty state for bookmark page
    - [x] add react router
- [x] add to app
- [x] check on mobile device
- [x] check accessibility
