### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by mwarnck** [mwarnck/capstone-project#9]
## Value proposition

**As a** user
**I need** I want my bookmarked drinks still there after a reload of the app
**to be able to** see my favorites drinks and to avoid searching them again

## Acceptance Criteria

- [x] The data remains even after a reload of the app
- [x] changes of the data will be stored in the local storage

## Tasks

- [x] add local storage (e.g. hook)
- [x] test the storage function
